---
title: "About This Website"
output: html_document
---

We aim to utilize our state-of-the-art devices, namely Swept-Source Optical Coherence Tomography Angiography (SS-OCTA), to evaluate the utility of such technologies in diagnosis and prognosis of ocular and systemic diseases, such as diabetic retinopathy and age-related macular degeneration. First introduced in 1991, Optical Coherence Tomography (OCT) marks one of the biggest advances in ophthalmic imaging, which came out of a collaboration between MIT, Mass Eye and Ear, and MGH. Early detection is often critical to treatment of diseases. Our current studies aim to identify novel and robust biomarkers, such as thinning of the vasculature, widening of the foveal avascular zone, and density within the multiple vascular layers, for patients with various retinal and choroidal disorders such as diabetic retinopathy and age-related macular degeneration and well as systemic diseases, such as Alzheimer’s disease, schizophrenia, and COVID-19 infection. Moreover, Artificial intelligence (AI) is changing healthcare and has many potential applications in the field of retina. With collaborations within the MGB system, our lab aims to investigate the utility of machine learning in the context of retinal imaging research. 